jenkins-slave:
  container_name: ${JENKINS_SLAVE_NAME}
  restart: always
  image: janhout/adop-jenkins-slave:0.1.7
  net: ${CUSTOM_NETWORK_NAME}
  privileged: true
  log_driver: "syslog"
  log_opt:
    syslog-address: "udp://${LOGSTASH_HOST}:25826"
    tag: "${JENKINS_SLAVE_NAME}"
  environment:
    SLAVE_NAME: ${JENKINS_SLAVE_NAME}
    SLAVE_LABELS: "aws ldap ftp java8 docker ftp ${NEW_SLAVE_LABELS}"
    SWARM_PASSWORD: ${SWARM_PASSWORD}
    SLAVE_EXECUTORS: ${SLAVE_EXECUTORS}
    INITIAL_ADMIN_USER: ${INITIAL_ADMIN_USER}
    INITIAL_ADMIN_PASSWORD: ${INITIAL_ADMIN_PASSWORD_PLAIN}